server:
  port: 8082
  tomcat:
    threads:
      max: 1
      min-spare: 1
    max-connections: 1
    accept-count: 1
    connection-timeout: 20000


spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: likelion-backend

custom:
#  env: dev
  port: ${PORT:8080}
  env: ${CUSTOM_ENV:dev}

